# Generated by Django 4.0.2 on 2023-05-01 10:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmaster',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
