# Generated by Django 4.0.2 on 2023-05-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_taskmaster_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmaster',
            name='userid',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
